name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: 2.2.2
  dio: 5.4.0
  pretty_dio_logger: 1.3.1
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  get_it: 7.6.6
  google_fonts: 6.1.0
  dartz: 0.10.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

